###
GET https://jc3mtrjl92.execute-api.us-east-1.amazonaws.com/dev

###
GET https://jc3mtrjl92.execute-api.us-east-1.amazonaws.com/dev/users

###
GET https://jc3mtrjl92.execute-api.us-east-1.amazonaws.com/dev/users/1

###
POST https://jc3mtrjl92.execute-api.us-east-1.amazonaws.com/dev/users
Content-Type: application/x-www-form-urlencoded

userId=1
&name=Oliver