###
GET https://nvkht8dhg5.execute-api.us-east-1.amazonaws.com/dev

###
POST https://nvkht8dhg5.execute-api.us-east-1.amazonaws.com/dev/users
Content-Type: application/x-www-form-urlencoded

userId=22
&name=John